.PHONY: clean All

All:
	@echo "----------Building project:[ MyMap - Debug ]----------"
	@cd "MyMap" && "$(MAKE)" -f  "MyMap.mk"
clean:
	@echo "----------Cleaning project:[ MyMap - Debug ]----------"
	@cd "MyMap" && "$(MAKE)" -f  "MyMap.mk" clean
